kind: pipeline
type: docker
name: release
platform:
  os: linux
  arch: amd64

steps:
- name: compress
  image: alpine:latest
  commands:
    - cd dist ; for dir in * ; do tar czf "$dir.tar.gz" "--directory=$dir" . ; done
- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: API_KEY
    base_url:
      from_secret: BASE_URL
    files: dist/*.tar.gz
    checksum: sha256

trigger:
  event:
  - tag
